export type QuestionCategory =
  | 'Test Rules'
  | 'Australia and its People'
  | 'Symbols and Days'
  | 'Democratic Beliefs'
  | 'Citizenship'
  | 'Government and Law'
  | 'Australian Values';

export type Question = {
  id: string;
  category: QuestionCategory;
  prompt: string;
  options: string[];
  answerIndex: number;
  explanation: string;
  valuesQuestion?: boolean;
};

export const PASS_MARK = 75;
export const PRACTICE_TEST_SIZE = 20;
export const REQUIRED_VALUES_CORRECT = 5;
export const OFFICIAL_SOURCE_URL =
  'https://immi.homeaffairs.gov.au/citizenship/test-and-interview/our-common-bond';

const CORE_QUESTIONS: Question[] = [
  {
    id: 'rules-01',
    category: 'Test Rules',
    prompt: 'How many randomly selected questions are in the Australian citizenship test?',
    options: ['10', '20', '30', '50'],
    answerIndex: 1,
    explanation: 'The citizenship test has 20 randomly selected multiple-choice questions.',
  },
  {
    id: 'rules-02',
    category: 'Test Rules',
    prompt: 'What overall mark is needed to pass the citizenship test?',
    options: ['50 per cent', '60 per cent', '75 per cent', '90 per cent'],
    answerIndex: 2,
    explanation: 'You need at least 75 per cent overall and must pass the values questions.',
  },
  {
    id: 'rules-03',
    category: 'Test Rules',
    prompt: 'How many Australian values questions are included in the citizenship test?',
    options: ['Two', 'Three', 'Five', 'Ten'],
    answerIndex: 2,
    explanation: 'The test includes five Australian values questions.',
    valuesQuestion: true,
  },
  {
    id: 'rules-04',
    category: 'Test Rules',
    prompt: 'What must happen with the five values questions for a person to pass?',
    options: [
      'At least one must be correct',
      'A majority must be correct',
      'All five must be answered correctly',
      'They are optional',
    ],
    answerIndex: 2,
    explanation: 'All five values questions must be answered correctly.',
    valuesQuestion: true,
  },
  {
    id: 'rules-05',
    category: 'Test Rules',
    prompt: 'In what language is the citizenship test conducted?',
    options: ['Any community language', 'English only', 'English or French', 'A language chosen by the applicant'],
    answerIndex: 1,
    explanation: 'The test is conducted in English.',
  },
  {
    id: 'people-01',
    category: 'Australia and its People',
    prompt: 'Who are Australia’s first inhabitants?',
    options: ['British settlers', 'Aboriginal and Torres Strait Islander peoples', 'European migrants', 'The First Fleet'],
    answerIndex: 1,
    explanation: 'Aboriginal and Torres Strait Islander peoples are Australia’s first inhabitants.',
  },
  {
    id: 'people-02',
    category: 'Australia and its People',
    prompt: 'Where are Torres Strait Islander people traditionally from?',
    options: [
      'The islands between northern Queensland and Papua New Guinea',
      'Tasmania only',
      'The south-west of Western Australia',
      'The Australian Alps',
    ],
    answerIndex: 0,
    explanation: 'Torres Strait Islander people are from islands between northern Queensland and Papua New Guinea.',
  },
  {
    id: 'people-03',
    category: 'Australia and its People',
    prompt: 'When did the First Fleet arrive from Great Britain?',
    options: ['25 April 1915', '1 January 1901', '26 January 1788', '15 November 2020'],
    answerIndex: 2,
    explanation: 'The First Fleet arrived on 26 January 1788.',
  },
  {
    id: 'people-04',
    category: 'Australia and its People',
    prompt: 'Who was the first Governor of New South Wales?',
    options: ['Captain James Cook', 'Captain Arthur Phillip', 'King Charles III', 'Sir Henry Parkes'],
    answerIndex: 1,
    explanation: 'Captain Arthur Phillip was the first Governor of New South Wales.',
  },
  {
    id: 'people-05',
    category: 'Australia and its People',
    prompt: 'What event began in 1851 after discoveries in New South Wales and Victoria?',
    options: ['Federation', 'The gold rush', 'The Anzac landing', 'The 1967 referendum'],
    answerIndex: 1,
    explanation: 'The gold rush began in 1851.',
  },
  {
    id: 'people-06',
    category: 'Australia and its People',
    prompt: 'Which non-European group arrived in large numbers during the gold rush?',
    options: ['Chinese people', 'Canadians', 'New Zealanders', 'Dutch traders'],
    answerIndex: 0,
    explanation: 'Chinese people were the first large group of migrants not from Europe.',
  },
  {
    id: 'people-07',
    category: 'Australia and its People',
    prompt: 'When did the colonies unite into the Commonwealth of Australia?',
    options: ['1788', '1851', '1901', '1967'],
    answerIndex: 2,
    explanation: 'The separate colonies united in 1901.',
  },
  {
    id: 'people-08',
    category: 'Australia and its People',
    prompt: 'What is Australia’s national language?',
    options: ['English', 'Latin', 'French', 'No language is valued'],
    answerIndex: 0,
    explanation: 'English is Australia’s national language.',
  },
  {
    id: 'people-09',
    category: 'Australia and its People',
    prompt: 'How many states does Australia have?',
    options: ['Four', 'Five', 'Six', 'Eight'],
    answerIndex: 2,
    explanation: 'Australia has six states.',
  },
  {
    id: 'people-10',
    category: 'Australia and its People',
    prompt: 'How many mainland territories are in Australia?',
    options: ['One', 'Two', 'Six', 'Eight'],
    answerIndex: 1,
    explanation: 'Australia has two mainland territories: the ACT and the Northern Territory.',
  },
  {
    id: 'people-11',
    category: 'Australia and its People',
    prompt: 'What is the capital city of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    answerIndex: 2,
    explanation: 'Canberra is Australia’s capital city.',
  },
  {
    id: 'people-12',
    category: 'Australia and its People',
    prompt: 'Which state was the first colony established by the British?',
    options: ['Victoria', 'New South Wales', 'South Australia', 'Tasmania'],
    answerIndex: 1,
    explanation: 'New South Wales was the first British colony.',
  },
  {
    id: 'people-13',
    category: 'Australia and its People',
    prompt: 'Which city is the capital of New South Wales?',
    options: ['Sydney', 'Canberra', 'Melbourne', 'Hobart'],
    answerIndex: 0,
    explanation: 'Sydney is the capital city of New South Wales.',
  },
  {
    id: 'people-14',
    category: 'Australia and its People',
    prompt: 'Which city is the capital of Victoria?',
    options: ['Adelaide', 'Darwin', 'Melbourne', 'Perth'],
    answerIndex: 2,
    explanation: 'Melbourne is the capital city of Victoria.',
  },
  {
    id: 'people-15',
    category: 'Australia and its People',
    prompt: 'Which city is the capital of Queensland?',
    options: ['Brisbane', 'Sydney', 'Hobart', 'Canberra'],
    answerIndex: 0,
    explanation: 'Brisbane is the capital city of Queensland.',
  },
  {
    id: 'people-16',
    category: 'Australia and its People',
    prompt: 'Which city is the capital of Western Australia?',
    options: ['Darwin', 'Perth', 'Adelaide', 'Melbourne'],
    answerIndex: 1,
    explanation: 'Perth is the capital city of Western Australia.',
  },
  {
    id: 'people-17',
    category: 'Australia and its People',
    prompt: 'Which city is the capital of South Australia?',
    options: ['Adelaide', 'Perth', 'Hobart', 'Brisbane'],
    answerIndex: 0,
    explanation: 'Adelaide is the capital city of South Australia.',
  },
  {
    id: 'people-18',
    category: 'Australia and its People',
    prompt: 'Which city is the capital of Tasmania?',
    options: ['Launceston', 'Hobart', 'Darwin', 'Canberra'],
    answerIndex: 1,
    explanation: 'Hobart is the capital city of Tasmania.',
  },
  {
    id: 'people-19',
    category: 'Australia and its People',
    prompt: 'Which city is the capital of the Northern Territory?',
    options: ['Alice Springs', 'Darwin', 'Canberra', 'Cairns'],
    answerIndex: 1,
    explanation: 'Darwin is the capital city of the Northern Territory.',
  },
  {
    id: 'symbols-01',
    category: 'Symbols and Days',
    prompt: 'Who can deliver an Acknowledgement of Country?',
    options: ['Only the Prime Minister', 'Only a court judge', 'Anyone', 'Only a police officer'],
    answerIndex: 2,
    explanation: 'Anyone can deliver an Acknowledgement of Country.',
  },
  {
    id: 'symbols-02',
    category: 'Symbols and Days',
    prompt: 'Who performs a Welcome to Country?',
    options: [
      'An Aboriginal or Torres Strait Islander custodian of the local region',
      'Any visitor to Australia',
      'Only the Governor-General',
      'Only a local council employee',
    ],
    answerIndex: 0,
    explanation: 'A Welcome to Country is performed by an Aboriginal or Torres Strait Islander custodian.',
  },
  {
    id: 'symbols-03',
    category: 'Symbols and Days',
    prompt: 'When is Australia Day celebrated?',
    options: ['1 January', '26 January', '25 April', '11 November'],
    answerIndex: 1,
    explanation: 'Australia Day is celebrated on 26 January.',
  },
  {
    id: 'symbols-04',
    category: 'Symbols and Days',
    prompt: 'What does Australia Day mark?',
    options: [
      'The first federal election',
      'The arrival of the First Fleet from Great Britain in 1788',
      'The end of World War I',
      'The opening of Parliament House',
    ],
    answerIndex: 1,
    explanation: 'Australia Day marks the arrival of the First Fleet in 1788.',
  },
  {
    id: 'symbols-05',
    category: 'Symbols and Days',
    prompt: 'When is Anzac Day commemorated?',
    options: ['25 April', '26 January', '1 January', '3 September'],
    answerIndex: 0,
    explanation: 'Anzac Day is commemorated on 25 April each year.',
  },
  {
    id: 'symbols-06',
    category: 'Symbols and Days',
    prompt: 'What does ANZAC stand for?',
    options: [
      'Australian and New Zealand Army Corps',
      'Australian National Zone Advisory Council',
      'Australia New Zealand Air Command',
      'Australian Navy and Zealand Coalition',
    ],
    answerIndex: 0,
    explanation: 'ANZAC stands for Australian and New Zealand Army Corps.',
  },
  {
    id: 'symbols-07',
    category: 'Symbols and Days',
    prompt: 'Which symbol appears in the top left corner of the Australian National Flag?',
    options: ['The Golden Wattle', 'The Union Jack', 'A kangaroo', 'The opal'],
    answerIndex: 1,
    explanation: 'The Union Jack appears in the top left corner.',
  },
  {
    id: 'symbols-08',
    category: 'Symbols and Days',
    prompt: 'How many points does the Commonwealth Star have?',
    options: ['Five', 'Six', 'Seven', 'Eight'],
    answerIndex: 2,
    explanation: 'The Commonwealth Star has seven points.',
  },
  {
    id: 'symbols-09',
    category: 'Symbols and Days',
    prompt: 'What does the Southern Cross on the Australian National Flag represent?',
    options: ['A group of stars seen in the southern sky', 'A court system', 'A state parliament', 'A desert region'],
    answerIndex: 0,
    explanation: 'The Southern Cross is a group of stars that can be seen in the southern sky.',
  },
  {
    id: 'symbols-10',
    category: 'Symbols and Days',
    prompt: 'What do the black and red halves of the Australian Aboriginal Flag represent?',
    options: [
      'Night and day',
      'Aboriginal peoples and the earth',
      'The sea and peace',
      'States and territories',
    ],
    answerIndex: 1,
    explanation: 'Black represents Aboriginal peoples and red represents the earth.',
  },
  {
    id: 'symbols-11',
    category: 'Symbols and Days',
    prompt: 'What does the yellow circle on the Australian Aboriginal Flag represent?',
    options: ['The sun', 'The moon', 'The sea', 'The Commonwealth Star'],
    answerIndex: 0,
    explanation: 'The yellow circle represents the sun.',
  },
  {
    id: 'symbols-12',
    category: 'Symbols and Days',
    prompt: 'What is the white dancer’s headdress on the Torres Strait Islander Flag a symbol for?',
    options: ['All Torres Strait Islanders', 'The High Court', 'The Senate', 'The gold rush'],
    answerIndex: 0,
    explanation: 'The headdress is a symbol for all Torres Strait Islanders.',
  },
  {
    id: 'symbols-13',
    category: 'Symbols and Days',
    prompt: 'What is Australia’s national flower?',
    options: ['Waratah', 'Golden wattle', 'Banksia', 'Sturt desert pea'],
    answerIndex: 1,
    explanation: 'The golden wattle is Australia’s national flower.',
  },
  {
    id: 'symbols-14',
    category: 'Symbols and Days',
    prompt: 'What are Australia’s national colours?',
    options: ['Red and blue', 'Black and white', 'Green and gold', 'Blue and white'],
    answerIndex: 2,
    explanation: 'Australia’s national colours are green and gold.',
  },
  {
    id: 'symbols-15',
    category: 'Symbols and Days',
    prompt: 'What is Australia’s national gemstone?',
    options: ['Diamond', 'Sapphire', 'Opal', 'Ruby'],
    answerIndex: 2,
    explanation: 'The opal is Australia’s national gemstone.',
  },
  {
    id: 'symbols-16',
    category: 'Symbols and Days',
    prompt: 'What is Australia’s national anthem?',
    options: ['Waltzing Matilda', 'Advance Australia Fair', 'God Save the King', 'I Am Australian'],
    answerIndex: 1,
    explanation: 'Advance Australia Fair is Australia’s national anthem.',
  },
  {
    id: 'democracy-01',
    category: 'Democratic Beliefs',
    prompt: 'What type of government system does Australia have?',
    options: ['Military rule', 'Parliamentary democracy', 'Absolute monarchy', 'One-party rule'],
    answerIndex: 1,
    explanation: 'Australia’s system of government is a parliamentary democracy.',
  },
  {
    id: 'democracy-02',
    category: 'Democratic Beliefs',
    prompt: 'In Australia, where does the power of government come from?',
    options: ['The Australian people', 'The police', 'Religious leaders', 'Business leaders'],
    answerIndex: 0,
    explanation: 'Government power comes from the people because citizens vote for representatives.',
  },
  {
    id: 'democracy-03',
    category: 'Democratic Beliefs',
    prompt: 'What does the Rule of Law mean?',
    options: [
      'Only elected officials must obey the law',
      'No person, group or religious rule is above the law',
      'Police can decide court cases',
      'Religious law is always higher than Australian law',
    ],
    answerIndex: 1,
    explanation: 'The Rule of Law means everyone is bound by the law.',
    valuesQuestion: true,
  },
  {
    id: 'democracy-04',
    category: 'Democratic Beliefs',
    prompt: 'How do Australians believe change should occur?',
    options: ['Through violence', 'Through discussion, peaceful persuasion and the democratic process', 'Only through the courts', 'Only through religious leaders'],
    answerIndex: 1,
    explanation: 'Australia rejects violence as a way to change minds or laws.',
    valuesQuestion: true,
  },
  {
    id: 'democracy-05',
    category: 'Democratic Beliefs',
    prompt: 'Freedom of speech allows people to criticise the government as long as they do what?',
    options: ['Leave Australia', 'Obey Australian laws', 'Join a party', 'Pay an extra tax'],
    answerIndex: 1,
    explanation: 'Freedom of speech must be exercised within Australian law.',
    valuesQuestion: true,
  },
  {
    id: 'democracy-06',
    category: 'Democratic Beliefs',
    prompt: 'What does freedom of association include?',
    options: [
      'Being forced to join a union',
      'The right to form and join legal organisations',
      'The right to damage property at protests',
      'The right to ignore the law',
    ],
    answerIndex: 1,
    explanation: 'People may form or join legal organisations and may also choose not to join.',
    valuesQuestion: true,
  },
  {
    id: 'democracy-07',
    category: 'Democratic Beliefs',
    prompt: 'What does it mean that Australia’s government is secular?',
    options: [
      'It operates separately from churches or other religious entities',
      'It has one official national religion',
      'Only religious leaders can make laws',
      'Citizens cannot follow a religion',
    ],
    answerIndex: 0,
    explanation: 'A secular government operates separately from religion.',
    valuesQuestion: true,
  },
  {
    id: 'democracy-08',
    category: 'Democratic Beliefs',
    prompt: 'If Australian law conflicts with a religious practice, which prevails?',
    options: ['Australian law', 'The religious practice', 'The applicant decides', 'Local custom always decides'],
    answerIndex: 0,
    explanation: 'Australian law prevails where there is a conflict.',
    valuesQuestion: true,
  },
  {
    id: 'citizenship-01',
    category: 'Citizenship',
    prompt: 'Which of these is a responsibility of Australian citizens?',
    options: ['Obey the laws of Australia', 'Own property', 'Join a political party', 'Have a passport'],
    answerIndex: 0,
    explanation: 'Australian citizens must obey Australian laws.',
  },
  {
    id: 'citizenship-02',
    category: 'Citizenship',
    prompt: 'Which citizens must vote in federal and state or territory elections?',
    options: ['Citizens aged 16 or over', 'Citizens aged 18 or over', 'Only property owners', 'Only people born in Australia'],
    answerIndex: 1,
    explanation: 'Australian citizens aged 18 years or over must vote.',
  },
  {
    id: 'citizenship-03',
    category: 'Citizenship',
    prompt: 'Which of these is a privilege of Australian citizenship?',
    options: ['Ignoring local laws', 'Applying for an Australian passport', 'Avoiding taxes', 'Refusing jury service when called'],
    answerIndex: 1,
    explanation: 'Australian citizens can apply for an Australian passport.',
  },
  {
    id: 'citizenship-04',
    category: 'Citizenship',
    prompt: 'What may Australian citizens apply for on behalf of children born overseas?',
    options: ['Citizenship by descent', 'A state governorship', 'A jury exemption', 'A referendum vote'],
    answerIndex: 0,
    explanation: 'Citizens can apply for children born overseas to become citizens by descent.',
  },
  {
    id: 'citizenship-05',
    category: 'Citizenship',
    prompt: 'What is jury service?',
    options: [
      'A responsibility for citizens if called to do so',
      'A paid political office',
      'A replacement for voting',
      'A ceremony at Parliament House',
    ],
    answerIndex: 0,
    explanation: 'Jury service, if called, is a responsibility of citizens aged 18 or over.',
  },
  {
    id: 'citizenship-06',
    category: 'Citizenship',
    prompt: 'What is another important way people contribute to the Australian community?',
    options: ['Paying tax', 'Refusing to vote', 'Ignoring council rules', 'Avoiding work'],
    answerIndex: 0,
    explanation: 'Taxes help fund services such as healthcare, education, defence and roads.',
  },
  {
    id: 'government-01',
    category: 'Government and Law',
    prompt: 'Which agency conducts federal elections and referendums?',
    options: ['Australian Taxation Office', 'Australian Electoral Commission', 'Australian Federal Police', 'Services Australia'],
    answerIndex: 1,
    explanation: 'The Australian Electoral Commission conducts federal elections and referendums.',
  },
  {
    id: 'government-02',
    category: 'Government and Law',
    prompt: 'What is a secret ballot?',
    options: [
      'A private vote where no one has to know your choice',
      'A vote only for ministers',
      'A vote held without candidates',
      'A public show of hands',
    ],
    answerIndex: 0,
    explanation: 'A secret ballot lets people vote privately and safely.',
  },
  {
    id: 'government-03',
    category: 'Government and Law',
    prompt: 'What happened on 1 January 1901?',
    options: [
      'The colonies became the Commonwealth of Australia',
      'The First Fleet landed',
      'Anzac troops landed at Gallipoli',
      'The citizenship test began',
    ],
    answerIndex: 0,
    explanation: 'On 1 January 1901, the colonies united as the Commonwealth of Australia.',
  },
  {
    id: 'government-04',
    category: 'Government and Law',
    prompt: 'What is the Australian Constitution?',
    options: [
      'The legal document setting out basic rules for Australian government',
      'A political party policy',
      'A local council plan',
      'A police handbook',
    ],
    answerIndex: 0,
    explanation: 'The Constitution sets out the basic rules for Australia’s government.',
  },
  {
    id: 'government-05',
    category: 'Government and Law',
    prompt: 'What does a referendum vote on?',
    options: [
      'A proposed change to the Australian Constitution',
      'The national anthem',
      'The appointment of police',
      'Local library hours',
    ],
    answerIndex: 0,
    explanation: 'A referendum is a vote on a proposed change to the Constitution.',
  },
  {
    id: 'government-06',
    category: 'Government and Law',
    prompt: 'What is needed for the Australian Constitution to change in a referendum?',
    options: ['A double majority', 'Only the Prime Minister’s approval', 'A police order', 'A local council vote'],
    answerIndex: 0,
    explanation: 'A double majority is needed: a national majority and a majority in a majority of states.',
  },
  {
    id: 'government-07',
    category: 'Government and Law',
    prompt: 'What is legislative power?',
    options: ['The power to make laws', 'The power to run courts', 'The power to command police only', 'The power to vote in elections'],
    answerIndex: 0,
    explanation: 'Legislative power is the power to make and change laws.',
  },
  {
    id: 'government-08',
    category: 'Government and Law',
    prompt: 'What is executive power?',
    options: ['The power to put laws into practice', 'The power to interpret laws', 'The power to count votes', 'The power to write the anthem'],
    answerIndex: 0,
    explanation: 'Executive power is the power to put laws into practice.',
  },
  {
    id: 'government-09',
    category: 'Government and Law',
    prompt: 'What is judicial power?',
    options: ['The power to interpret and apply the law', 'The power to collect tax', 'The power to elect senators', 'The power to form a party'],
    answerIndex: 0,
    explanation: 'Judicial power belongs to courts and judges who interpret and apply the law.',
  },
  {
    id: 'government-10',
    category: 'Government and Law',
    prompt: 'Who is Australia’s Head of State according to the booklet?',
    options: ['The Prime Minister', 'The King of Australia', 'The Chief Justice', 'The Leader of the Opposition'],
    answerIndex: 1,
    explanation: 'Australia’s Head of State is the King of Australia.',
  },
  {
    id: 'government-11',
    category: 'Government and Law',
    prompt: 'Who represents the Head of State in Australia?',
    options: ['The Governor-General', 'The Premier', 'The Mayor', 'The Speaker only'],
    answerIndex: 0,
    explanation: 'The Governor-General represents the Head of State in Australia.',
  },
  {
    id: 'government-12',
    category: 'Government and Law',
    prompt: 'What is Australia’s system as a constitutional monarchy?',
    options: [
      'The King is Head of State but acts in accordance with the Constitution',
      'The King makes all day-to-day laws alone',
      'There is no Parliament',
      'Only governors can vote',
    ],
    answerIndex: 0,
    explanation: 'In a constitutional monarchy, the Head of State acts in accordance with the Constitution.',
  },
  {
    id: 'government-13',
    category: 'Government and Law',
    prompt: 'What is Royal Assent?',
    options: [
      'The Governor-General signing a Bill into law',
      'A vote for a councillor',
      'The start of a criminal trial',
      'A local road permit',
    ],
    answerIndex: 0,
    explanation: 'Royal Assent is when the Governor-General signs a Bill so it becomes law.',
  },
  {
    id: 'government-14',
    category: 'Government and Law',
    prompt: 'What are the two Houses of the Australian Parliament?',
    options: [
      'The House of Representatives and the Senate',
      'The High Court and the Cabinet',
      'The Premier and the Mayor',
      'The AEC and the AFP',
    ],
    answerIndex: 0,
    explanation: 'The Australian Parliament has the House of Representatives and the Senate.',
  },
  {
    id: 'government-15',
    category: 'Government and Law',
    prompt: 'What is another name for the House of Representatives?',
    options: ['The Lower House', 'The States’ House', 'The House of Review', 'The Cabinet'],
    answerIndex: 0,
    explanation: 'The House of Representatives is also called the Lower House or the People’s House.',
  },
  {
    id: 'government-16',
    category: 'Government and Law',
    prompt: 'What is another name for the Senate?',
    options: ['The Upper House', 'The People’s House', 'The Local House', 'The Court House'],
    answerIndex: 0,
    explanation: 'The Senate is also called the Upper House, House of Review or States’ House.',
  },
  {
    id: 'government-17',
    category: 'Government and Law',
    prompt: 'How many senators are there in total?',
    options: ['12', '50', '76', '150'],
    answerIndex: 2,
    explanation: 'There are 76 senators.',
  },
  {
    id: 'government-18',
    category: 'Government and Law',
    prompt: 'How many senators does each state elect?',
    options: ['Two', 'Six', 'Twelve', 'Twenty'],
    answerIndex: 2,
    explanation: 'Each state elects 12 senators.',
  },
  {
    id: 'government-19',
    category: 'Government and Law',
    prompt: 'How many senators do the ACT and Northern Territory each elect?',
    options: ['One', 'Two', 'Six', 'Twelve'],
    answerIndex: 1,
    explanation: 'The ACT and Northern Territory each elect two senators.',
  },
  {
    id: 'government-20',
    category: 'Government and Law',
    prompt: 'Who is the leader of the Australian Government?',
    options: ['Prime Minister', 'Premier', 'Chief Minister', 'Mayor'],
    answerIndex: 0,
    explanation: 'The Prime Minister is the leader of the Australian Government.',
  },
  {
    id: 'government-21',
    category: 'Government and Law',
    prompt: 'Who is the leader of a state government?',
    options: ['Premier', 'Chief Minister', 'Mayor', 'Senator'],
    answerIndex: 0,
    explanation: 'A Premier leads a state government.',
  },
  {
    id: 'government-22',
    category: 'Government and Law',
    prompt: 'Who is the leader of a territory government?',
    options: ['Chief Minister', 'Premier', 'Governor-General', 'Councillor'],
    answerIndex: 0,
    explanation: 'A Chief Minister leads a territory government.',
  },
  {
    id: 'government-23',
    category: 'Government and Law',
    prompt: 'Which level of government is responsible for immigration and citizenship?',
    options: ['Australian Government', 'Local government', 'State government only', 'Private organisations'],
    answerIndex: 0,
    explanation: 'The Australian Government is responsible for immigration and citizenship.',
  },
  {
    id: 'government-24',
    category: 'Government and Law',
    prompt: 'Which level of government is responsible for defence?',
    options: ['Australian Government', 'Local council', 'State government only', 'A shire'],
    answerIndex: 0,
    explanation: 'Defence is an Australian Government responsibility.',
  },
  {
    id: 'government-25',
    category: 'Government and Law',
    prompt: 'Which level of government is primarily responsible for hospitals and schools?',
    options: ['State and territory governments', 'Local government only', 'The Australian Government only', 'Political parties'],
    answerIndex: 0,
    explanation: 'State and territory governments are primarily responsible for hospitals and schools.',
  },
  {
    id: 'government-26',
    category: 'Government and Law',
    prompt: 'Which level of government is responsible for local roads, footpaths and rubbish collection?',
    options: ['Local governments', 'The Senate', 'The High Court', 'The Australian Defence Force'],
    answerIndex: 0,
    explanation: 'Local governments provide many local services including roads, footpaths and rubbish collection.',
  },
  {
    id: 'government-27',
    category: 'Government and Law',
    prompt: 'What is a political party?',
    options: [
      'A group of people with similar ideas about how a country should be governed',
      'A court that hears criminal trials',
      'A police unit',
      'A citizenship ceremony',
    ],
    answerIndex: 0,
    explanation: 'Political parties work to turn shared ideas into laws.',
  },
  {
    id: 'government-28',
    category: 'Government and Law',
    prompt: 'After a federal election, who usually forms government?',
    options: [
      'The party or coalition with a majority in the House of Representatives',
      'The party with the fewest members',
      'The High Court',
      'The local councils',
    ],
    answerIndex: 0,
    explanation: 'Government is usually formed by the party or coalition with a majority in the House of Representatives.',
  },
  {
    id: 'government-29',
    category: 'Government and Law',
    prompt: 'What is a Bill?',
    options: ['A proposed new law or change to an existing law', 'A fine for not voting', 'A court sentence', 'A passport form only'],
    answerIndex: 0,
    explanation: 'A Bill is a proposal to introduce or change a law.',
  },
  {
    id: 'government-30',
    category: 'Government and Law',
    prompt: 'Who decides whether a person has broken the law?',
    options: ['The courts', 'The media', 'A political party', 'A neighbour'],
    answerIndex: 0,
    explanation: 'Independent courts decide whether a person has or has not broken the law.',
  },
  {
    id: 'government-31',
    category: 'Government and Law',
    prompt: 'In Australia’s court system, people are considered innocent until what happens?',
    options: ['They are found guilty in a court', 'Police question them', 'The media names them', 'A neighbour complains'],
    answerIndex: 0,
    explanation: 'People are considered innocent until found guilty in a court.',
  },
  {
    id: 'government-32',
    category: 'Government and Law',
    prompt: 'What is the role of a jury?',
    options: [
      'To decide if a person is innocent or guilty in some court cases',
      'To write new laws',
      'To appoint the Prime Minister',
      'To run elections',
    ],
    answerIndex: 0,
    explanation: 'A jury decides whether a person is innocent or guilty in some cases.',
  },
  {
    id: 'government-33',
    category: 'Government and Law',
    prompt: 'What is the national police force called?',
    options: ['Australian Federal Police', 'Australian Electoral Commission', 'Australian Public Service', 'Australian Human Rights Commission'],
    answerIndex: 0,
    explanation: 'Australia’s national police force is the Australian Federal Police.',
  },
  {
    id: 'government-34',
    category: 'Government and Law',
    prompt: 'Is it a crime to offer a bribe to a police officer in Australia?',
    options: ['Yes', 'No', 'Only in federal elections', 'Only if the bribe is money'],
    answerIndex: 0,
    explanation: 'It is a serious crime to bribe or offer a bribe to the police.',
  },
  {
    id: 'government-35',
    category: 'Government and Law',
    prompt: 'What must people have to drive a car in Australia?',
    options: ['A local driver’s licence and a registered car', 'Only a passport', 'Only a citizenship certificate', 'A letter from a mayor'],
    answerIndex: 0,
    explanation: 'Drivers must have a local driver’s licence and the car must be registered.',
  },
  {
    id: 'government-36',
    category: 'Government and Law',
    prompt: 'Which driving behaviour is against Australian traffic law?',
    options: ['Using a hand-held mobile device while driving', 'Wearing a seatbelt', 'Registering a car', 'Using approved child seats'],
    answerIndex: 0,
    explanation: 'It is against the law to use a hand-held mobile device while driving.',
  },
  {
    id: 'values-01',
    category: 'Australian Values',
    prompt: 'Which values are central to Australia’s community according to the booklet?',
    options: [
      'Freedom, respect, fairness and equality of opportunity',
      'Wealth, status and obedience to one religion',
      'Violence and intimidation',
      'Class distinction and special privilege',
    ],
    answerIndex: 0,
    explanation: 'Australian values are based on freedom, respect, fairness and equality of opportunity.',
    valuesQuestion: true,
  },
  {
    id: 'values-02',
    category: 'Australian Values',
    prompt: 'What should a person do if no one is watching them?',
    options: ['Still follow the law', 'Ignore the law', 'Only follow personal rules', 'Wait for police instructions'],
    answerIndex: 0,
    explanation: 'Under Australian values, people should obey the law at all times.',
    valuesQuestion: true,
  },
  {
    id: 'values-03',
    category: 'Australian Values',
    prompt: 'Is it acceptable in Australia to promote violence against another person or group?',
    options: ['No', 'Yes, if you disagree with them', 'Only online', 'Only during elections'],
    answerIndex: 0,
    explanation: 'Promoting violence is against Australian values and law.',
    valuesQuestion: true,
  },
  {
    id: 'values-04',
    category: 'Australian Values',
    prompt: 'Can people in Australia be forced to join an organisation?',
    options: ['No', 'Yes, if it is political', 'Yes, if it is cultural', 'Only if they are citizens'],
    answerIndex: 0,
    explanation: 'People are free to join or leave legal groups voluntarily.',
    valuesQuestion: true,
  },
  {
    id: 'values-05',
    category: 'Australian Values',
    prompt: 'Does Australia have an official national religion?',
    options: ['No', 'Yes, Christianity', 'Yes, Judaism', 'Yes, all religions are official'],
    answerIndex: 0,
    explanation: 'Australia has no official national religion.',
    valuesQuestion: true,
  },
  {
    id: 'values-06',
    category: 'Australian Values',
    prompt: 'What legal status do religious laws have in Australia?',
    options: ['No legal status', 'Higher status than Australian law', 'Equal status to traffic laws only', 'They apply only in courts'],
    answerIndex: 0,
    explanation: 'Religious laws have no legal status in Australia.',
    valuesQuestion: true,
  },
  {
    id: 'values-07',
    category: 'Australian Values',
    prompt: 'Which statement reflects equality under Australian law?',
    options: [
      'People of different faiths receive the same legal treatment',
      'One religion receives special legal treatment',
      'Only citizens are protected by law',
      'Men have more rights than women',
    ],
    answerIndex: 0,
    explanation: 'Australian society values equal rights regardless of religion or background.',
    valuesQuestion: true,
  },
  {
    id: 'values-08',
    category: 'Australian Values',
    prompt: 'Do men and women have equal rights in Australia?',
    options: ['Yes', 'No', 'Only in federal elections', 'Only in courts'],
    answerIndex: 0,
    explanation: 'Men and women have equal rights in Australia.',
    valuesQuestion: true,
  },
  {
    id: 'values-09',
    category: 'Australian Values',
    prompt: 'Is physical violence against a spouse or partner acceptable in Australia?',
    options: ['No, it is a criminal offence', 'Yes, if married', 'Yes, if private', 'Only if no one reports it'],
    answerIndex: 0,
    explanation: 'Physical violence against a spouse or partner is never acceptable and is a criminal offence.',
    valuesQuestion: true,
  },
  {
    id: 'values-10',
    category: 'Australian Values',
    prompt: 'Is divorce acceptable in Australia?',
    options: ['Yes', 'No', 'Only for citizens by birth', 'Only with government permission'],
    answerIndex: 0,
    explanation: 'Either spouse may apply to the courts for a divorce.',
    valuesQuestion: true,
  },
  {
    id: 'values-11',
    category: 'Australian Values',
    prompt: 'What does a fair go mean?',
    options: [
      'Equal opportunity to achieve success regardless of background',
      'Everyone receives the same job',
      'Only wealthy people can succeed',
      'Class distinctions are protected by law',
    ],
    answerIndex: 0,
    explanation: 'A fair go means equal opportunity and no formal class distinctions.',
    valuesQuestion: true,
  },
  {
    id: 'values-12',
    category: 'Australian Values',
    prompt: 'What should determine who gets a job?',
    options: ['Skills and experience', 'Gender or wealth', 'Ethnicity', 'Family status only'],
    answerIndex: 0,
    explanation: 'A person should get a job based on skills and experience.',
    valuesQuestion: true,
  },
  {
    id: 'values-13',
    category: 'Australian Values',
    prompt: 'What does mutual respect and tolerance include?',
    options: [
      'Listening to others and respecting different views',
      'Silencing all disagreement',
      'Using intimidation to win arguments',
      'Refusing lawful police requests',
    ],
    answerIndex: 0,
    explanation: 'Australians value peaceful disagreement, mutual respect and tolerance.',
    valuesQuestion: true,
  },
  {
    id: 'values-14',
    category: 'Australian Values',
    prompt: 'Does racism have a place in Australia?',
    options: ['No', 'Yes, at sporting events', 'Yes, online only', 'Only during elections'],
    answerIndex: 0,
    explanation: 'Racism has no place in Australia.',
    valuesQuestion: true,
  },
  {
    id: 'values-15',
    category: 'Australian Values',
    prompt: 'What does Australia expect of people living in Australia when they are able?',
    options: [
      'Try to support themselves and their families',
      'Avoid contributing to society',
      'Refuse to learn English',
      'Ignore community safety',
    ],
    answerIndex: 0,
    explanation: 'Everyone has a responsibility to try to support themselves and their families when able.',
    valuesQuestion: true,
  },
  {
    id: 'values-16',
    category: 'Australian Values',
    prompt: 'What does mateship include?',
    options: ['Helping each other in times of need', 'Breaking laws for friends', 'Avoiding community service', 'Ignoring neighbours'],
    answerIndex: 0,
    explanation: 'Mateship includes helping others in times of need.',
    valuesQuestion: true,
  },
  {
    id: 'values-17',
    category: 'Australian Values',
    prompt: 'Why is learning English important in Australia?',
    options: [
      'It helps with education, work, integration and social cohesion',
      'It replaces all other languages',
      'It lets people ignore laws',
      'It is needed only for tourists',
    ],
    answerIndex: 0,
    explanation: 'English is an important unifying element and helps people participate in society.',
    valuesQuestion: true,
  },
  {
    id: 'values-18',
    category: 'Australian Values',
    prompt: 'What should people do if they suspect a serious crime is being planned?',
    options: ['Report it to Australian government authorities as soon as possible', 'Ignore it', 'Post rumours online', 'Wait until after the crime'],
    answerIndex: 0,
    explanation: 'Reporting suspected serious crime helps protect the safety of the community.',
    valuesQuestion: true,
  },
  {
    id: 'values-19',
    category: 'Australian Values',
    prompt: 'Is online abuse accepted in Australia?',
    options: ['No', 'Yes', 'Only if anonymous', 'Only if it happens overseas'],
    answerIndex: 0,
    explanation: 'Online abuse is not accepted and many forms are illegal.',
    valuesQuestion: true,
  },
  {
    id: 'values-20',
    category: 'Australian Values',
    prompt: 'If an Australian citizen also has another citizenship, what must they do while in Australia?',
    options: ['Follow all Australian laws at all times', 'Follow only the other country’s laws', 'Choose which laws to follow', 'Avoid voting forever'],
    answerIndex: 0,
    explanation: 'Australian citizens in Australia must follow all Australian laws at all times.',
    valuesQuestion: true,
  },
];

const CAPITAL_FACTS = [
  { place: 'New South Wales', capital: 'Sydney' },
  { place: 'Victoria', capital: 'Melbourne' },
  { place: 'Queensland', capital: 'Brisbane' },
  { place: 'Western Australia', capital: 'Perth' },
  { place: 'South Australia', capital: 'Adelaide' },
  { place: 'Tasmania', capital: 'Hobart' },
  { place: 'Australian Capital Territory', capital: 'Canberra' },
  { place: 'Northern Territory', capital: 'Darwin' },
];

const ROLE_FACTS = [
  { role: 'King of Australia', definition: 'Australia’s Head of State' },
  { role: 'Governor-General', definition: 'the representative of the Head of State in Australia' },
  { role: 'Governor', definition: 'the representative of the Head of State in each Australian state' },
  { role: 'Prime Minister', definition: 'the leader of the Australian Government' },
  { role: 'Premier', definition: 'the leader of a state government' },
  { role: 'Chief Minister', definition: 'the leader of a territory government' },
  { role: 'Government minister', definition: 'a parliamentarian responsible for an area of government' },
  { role: 'Member of Parliament', definition: 'an elected representative in the Australian Parliament or a state parliament' },
  { role: 'Senator', definition: 'an elected representative of a state or territory in the Australian Parliament' },
  { role: 'Mayor or Shire President', definition: 'the leader of a local government' },
  { role: 'Councillor', definition: 'an elected member of a local council' },
];

const RESPONSIBILITY_FACTS = [
  { item: 'taxation', level: 'Australian Government' },
  { item: 'national economic management', level: 'Australian Government' },
  { item: 'immigration and citizenship', level: 'Australian Government' },
  { item: 'employment assistance', level: 'Australian Government' },
  { item: 'postal services and the communications network', level: 'Australian Government' },
  { item: 'social security payments', level: 'Australian Government' },
  { item: 'defence', level: 'Australian Government' },
  { item: 'trade and commerce', level: 'Australian Government' },
  { item: 'airports and air safety', level: 'Australian Government' },
  { item: 'foreign affairs', level: 'Australian Government' },
  { item: 'hospitals and health services', level: 'State and territory governments' },
  { item: 'schools', level: 'State and territory governments' },
  { item: 'roads and railways', level: 'State and territory governments' },
  { item: 'forestry', level: 'State and territory governments' },
  { item: 'police and ambulance services', level: 'State and territory governments' },
  { item: 'public transport', level: 'State and territory governments' },
  { item: 'street signs and traffic controls', level: 'Local governments' },
  { item: 'local roads, footpaths and bridges', level: 'Local governments' },
  { item: 'drains', level: 'Local governments' },
  { item: 'parks, playgrounds, swimming pools and sports grounds', level: 'Local governments' },
  { item: 'camping grounds and caravan parks', level: 'Local governments' },
  { item: 'food and meat inspection', level: 'Local governments' },
  { item: 'noise and animal control', level: 'Local governments' },
  { item: 'rubbish collection', level: 'Local governments' },
  { item: 'local libraries, halls and community centres', level: 'Local governments' },
  { item: 'certain child-care and aged-care issues', level: 'Local governments' },
  { item: 'building permits', level: 'Local governments' },
  { item: 'social planning', level: 'Local governments' },
  { item: 'local environmental issues', level: 'Local governments' },
];

const GLOSSARY_FACTS = [
  { term: 'Aboriginal and Torres Strait Islander peoples', definition: 'the original inhabitants of the land in Australia', category: 'Australia and its People' as const },
  { term: 'Australian Human Rights Commission', definition: 'an independent Commission that investigates complaints about discrimination and human rights breaches', category: 'Government and Law' as const },
  { term: 'Australian Public Service', definition: 'government departments and the people employed by them', category: 'Citizenship' as const },
  { term: 'civil unrest', definition: 'demonstrations and riots by large numbers of people, usually protesting against a government decision or policy', category: 'Government and Law' as const },
  { term: 'coalition', definition: 'the joining of two or more political parties, usually to form a government or opposition', category: 'Government and Law' as const },
  { term: 'commission', definition: 'a group of people with an official responsibility', category: 'Government and Law' as const },
  { term: 'Constitution', definition: 'the supreme law of Australia by which the government must abide', category: 'Government and Law' as const },
  { term: 'constitutional monarchy', definition: 'a country with a king or queen as head of state whose powers are limited by the Constitution', category: 'Government and Law' as const },
  { term: 'court', definition: 'a place where legal cases are heard by a judge or magistrate', category: 'Government and Law' as const },
  { term: 'criminal trial', definition: 'a court hearing of facts to decide if a person is guilty or not guilty of a crime', category: 'Government and Law' as const },
  { term: 'cyber abuse', definition: 'behaviour using technology to threaten, intimidate, harass or humiliate someone with intent to hurt them', category: 'Australian Values' as const },
  { term: 'democracy', definition: 'government by the people through elected representatives', category: 'Democratic Beliefs' as const },
  { term: 'domestic and family violence', definition: 'behaviour or threats that aim to control a partner by causing fear or threatening safety', category: 'Australian Values' as const },
  { term: 'drug trafficking', definition: 'carrying or buying drugs to sell illegally', category: 'Government and Law' as const },
  { term: 'election', definition: 'a process where citizens choose people to represent them in Parliament', category: 'Government and Law' as const },
  { term: 'electoral roll', definition: 'the list of people registered to vote in an election or referendum', category: 'Government and Law' as const },
  { term: 'electorate', definition: 'a district of voters who elect politicians in the House of Representatives', category: 'Government and Law' as const },
  { term: 'enforce the law', definition: 'to make sure that people follow the law', category: 'Government and Law' as const },
  { term: 'equality', definition: 'the same in status', category: 'Australian Values' as const },
  { term: 'executive power', definition: 'the power and authority to administer the laws', category: 'Government and Law' as const },
  { term: 'fair go', definition: 'equal opportunity to achieve success regardless of background', category: 'Australian Values' as const },
  { term: 'federation', definition: 'the union of colonies into one nation while colonies retain certain powers', category: 'Australia and its People' as const },
  { term: 'First Fleet', definition: 'the group of 11 ships from Britain that established a convict settlement in New South Wales', category: 'Australia and its People' as const },
  { term: 'floral emblem', definition: 'national flower', category: 'Symbols and Days' as const },
  { term: 'forced marriage', definition: 'a marriage where one or both people did not have a free choice', category: 'Australian Values' as const },
  { term: 'icon', definition: 'a well-known image', category: 'Symbols and Days' as const },
  { term: 'Indigenous', definition: 'the Aboriginal and/or Torres Strait Islander peoples of Australia', category: 'Australia and its People' as const },
  { term: 'integration', definition: 'the process where migrants adapt so they can participate in and contribute to society', category: 'Australian Values' as const },
  { term: 'judicial power', definition: 'the power and authority to interpret and apply the laws', category: 'Government and Law' as const },
  { term: 'legislative power', definition: 'the power and authority to make and change laws', category: 'Government and Law' as const },
  { term: 'liberties', definition: 'personal freedom and independence', category: 'Democratic Beliefs' as const },
  { term: 'magistrate', definition: 'a judge of a lower court', category: 'Government and Law' as const },
  { term: 'mateship', definition: 'helping and receiving help from others, especially in difficult times', category: 'Australian Values' as const },
  { term: 'national anthem', definition: 'national song', category: 'Symbols and Days' as const },
  { term: 'parliamentary democracy', definition: 'a system based on regular election of representatives to parliament by citizens', category: 'Democratic Beliefs' as const },
  { term: 'political party', definition: 'a group of people with similar ideas about how a country should be governed', category: 'Government and Law' as const },
  { term: 'racism', definition: 'prejudice, discrimination, harassment or hatred directed at someone because of race, colour, national or ethnic origin', category: 'Australian Values' as const },
  { term: 'referendum', definition: 'a vote by all voters on a proposed change to the Australian Constitution', category: 'Government and Law' as const },
  { term: 'representative', definition: 'a person who acts or speaks for others', category: 'Government and Law' as const },
  { term: 'respect', definition: 'showing consideration for someone as a person, or for a decision they have made', category: 'Australian Values' as const },
  { term: 'Rule of Law', definition: 'all people, including citizens and the government, are bound by the law', category: 'Australian Values' as const },
  { term: 'secret ballot', definition: 'a private voting system where no one can influence or pressure a voter', category: 'Government and Law' as const },
  { term: 'secular', definition: 'separate from religion', category: 'Democratic Beliefs' as const },
  { term: 'self-sufficient', definition: 'able to provide for your own needs without help from other people', category: 'Australian Values' as const },
  { term: 'social security', definition: 'government pensions or benefits for unemployed people, disabled people, elderly people and others in need', category: 'Citizenship' as const },
  { term: 'The Australian Taxation Office', definition: 'the agency that manages tax and superannuation systems that fund services for Australians', category: 'Citizenship' as const },
  { term: 'values', definition: 'principles that help a person decide what is right and wrong and how to act', category: 'Australian Values' as const },
  { term: 'volunteer', definition: 'a person who gives time to a person or organisation without expecting payment', category: 'Australian Values' as const },
];

function otherOptions(correct: string, pool: string[], count = 3) {
  return pool.filter((item) => item !== correct).slice(0, count);
}

const CAPITAL_QUESTIONS: Question[] = CAPITAL_FACTS.flatMap((fact, index) => [
  {
    id: `capital-${index + 1}-a`,
    category: 'Australia and its People',
    prompt: `What is the capital city of ${fact.place}?`,
    options: [fact.capital, ...otherOptions(fact.capital, CAPITAL_FACTS.map((item) => item.capital))],
    answerIndex: 0,
    explanation: `${fact.capital} is the capital city of ${fact.place}.`,
  },
  {
    id: `capital-${index + 1}-b`,
    category: 'Australia and its People',
    prompt: `${fact.capital} is the capital city of which state or territory?`,
    options: [fact.place, ...otherOptions(fact.place, CAPITAL_FACTS.map((item) => item.place))],
    answerIndex: 0,
    explanation: `${fact.capital} is the capital city of ${fact.place}.`,
  },
]);

const ROLE_QUESTIONS: Question[] = ROLE_FACTS.map((fact, index) => ({
  id: `role-${index + 1}`,
  category: 'Government and Law',
  prompt: `In Australia, who is ${fact.definition}?`,
  options: [fact.role, ...otherOptions(fact.role, ROLE_FACTS.map((item) => item.role))],
  answerIndex: 0,
  explanation: `${fact.role} is ${fact.definition}.`,
}));

const RESPONSIBILITY_QUESTIONS: Question[] = RESPONSIBILITY_FACTS.map((fact, index) => ({
  id: `responsibility-${index + 1}`,
  category: 'Government and Law',
  prompt: `Which level of government is responsible for ${fact.item}?`,
  options: [fact.level, ...otherOptions(fact.level, ['Australian Government', 'State and territory governments', 'Local governments'])],
  answerIndex: 0,
  explanation: `${fact.item} is listed as a responsibility of ${fact.level}.`,
}));

const GLOSSARY_QUESTIONS: Question[] = GLOSSARY_FACTS.flatMap((fact, index) => [
  {
    id: `glossary-${index + 1}-term`,
    category: fact.category,
    prompt: `What does "${fact.term}" mean in the citizenship booklet?`,
    options: [fact.definition, ...otherOptions(fact.definition, GLOSSARY_FACTS.map((item) => item.definition))],
    answerIndex: 0,
    explanation: `"${fact.term}" means ${fact.definition}.`,
    valuesQuestion: fact.category === 'Australian Values',
  },
  {
    id: `glossary-${index + 1}-definition`,
    category: fact.category,
    prompt: `Which term means "${fact.definition}"?`,
    options: [fact.term, ...otherOptions(fact.term, GLOSSARY_FACTS.map((item) => item.term))],
    answerIndex: 0,
    explanation: `The correct term is "${fact.term}".`,
    valuesQuestion: fact.category === 'Australian Values',
  },
]);

export const QUESTIONS: Question[] = [
  ...CORE_QUESTIONS,
  ...CAPITAL_QUESTIONS,
  ...ROLE_QUESTIONS,
  ...RESPONSIBILITY_QUESTIONS,
  ...GLOSSARY_QUESTIONS,
];
